import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800'], 
  variable: '--font-montserrat', 
})

export const metadata = {
  title: "Co-Criativo - Membros",
  description: "Generated by create next app",
  icons: {
    icon: "/simbolo.png",
    apple: "/simbolo.png",
    shortcut: "/simbolo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.className}>
      <body
        className={` antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
